/**
  ******************************************************************************
  * @file    app_bsp.c
  * @brief   Application overrides of CubeMX BSP defaults (regeneration-safe).
  *
  *          custom_bus.c is regenerated by CubeMX and declares MX_SPI1_Init() __weak.
  *          The generated default is wrong for the BlueNRG-2 (4-bit frames, 40 MHz);
  *          this strong definition replaces it.
  ******************************************************************************
  */

#include "custom_bus.h"

/* SPI1 settings from the ST X-CUBE-BLE2 BlueNRG-M2SP reference application:
 * 8-bit frames, CPOL low/CPHA second edge (SPI mode 1), conservative clock. */
HAL_StatusTypeDef MX_SPI1_Init(SPI_HandleTypeDef* hspi)
{
  HAL_StatusTypeDef ret = HAL_OK;

  hspi->Instance = SPI1;
  hspi->Init.Mode = SPI_MODE_MASTER;
  hspi->Init.Direction = SPI_DIRECTION_2LINES;
  hspi->Init.DataSize = SPI_DATASIZE_8BIT;
  hspi->Init.CLKPolarity = SPI_POLARITY_LOW;
  hspi->Init.CLKPhase = SPI_PHASE_2EDGE;
  hspi->Init.NSS = SPI_NSS_SOFT;
  hspi->Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_64;
  hspi->Init.FirstBit = SPI_FIRSTBIT_MSB;
  hspi->Init.TIMode = SPI_TIMODE_DISABLE;
  hspi->Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;
  hspi->Init.CRCPolynomial = 7;
  hspi->Init.CRCLength = SPI_CRC_LENGTH_DATASIZE;
  hspi->Init.NSSPMode = SPI_NSS_PULSE_DISABLE;
  if (HAL_SPI_Init(hspi) != HAL_OK)
  {
    ret = HAL_ERROR;
  }

  return ret;
}
